In [1]:
from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')
!pip install biopython

Mounted at /content/drive
Collecting biopython
  Downloading biopython-1.88-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Downloading biopython-1.88-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 8.5 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.88

In [3]:
from Bio import SeqIO
import pandas as pd

In [6]:
import pandas as pd
blast_df=pd.read_csv("/content/drive/MyDrive/Subtractive Genomics Approach/blast_results_full(1).csv")
blast_df

,protein_id,human_match_id,e_value,human_identity_percent,bit_score,alignment_length,mismatches
0,sp|A0A089QRB9|MSL3_MYCTU,tr|A0ACI8U4L2|A0ACI8U4L2_HUMAN,1.570000e-75,27.675,283.0,1084,674
1,sp|A0A089QRB9|MSL3_MYCTU,tr|A0ACI8U4L2|A0ACI8U4L2_HUMAN,5.600000e-53,32.364,209.0,550,322
2,sp|A0A089QRB9|MSL3_MYCTU,tr|A0A0U1RQF0|A0A0U1RQF0_HUMAN,2.150000e-75,27.675,282.0,1084,674
3,sp|A0A089QRB9|MSL3_MYCTU,tr|A0A0U1RQF0|A0A0U1RQF0_HUMAN,1.040000e-53,30.256,211.0,704,401
4,sp|A0A089QRB9|MSL3_MYCTU,sp|P49327|FAS_HUMAN,2.350000e-75,27.675,282.0,1084,674
...,...,...,...,...,...,...,...
78253,tr|Q79FY4|Q79FY4_MYCTU,tr|A0ACI8RCW8|A0ACI8RCW8_HUMAN,9.740000e-10,30.380,59.7,158,93
78254,tr|Q79FY4|Q79FY4_MYCTU,tr|A0ACI8RGK0|A0ACI8RGK0_HUMAN,9.740000e-10,30.380,59.7,158,93
78255,tr|Q79FY4|Q79FY4_MYCTU,tr|A0ACI8S5X4|A0ACI8S5X4_HUMAN,1.820000e-07,29.655,53.1,145,87
78256,tr|Q79FY4|Q79FY4_MYCTU,tr|A0ACI8RPL3|A0ACI8RPL3_HUMAN,1.890000e-07,29.655,52.8,145,87
78257,tr|Q79FY4|Q79FY4_MYCTU,tr|A0ACI8RTE2|A0ACI8RTE2_HUMAN,1.910000e-07,29.655,52.8,145,87

In [7]:

homo_ids = blast_df[blast_df['e_value'] <= 1e-4]['protein_id']

homo_ids.head()

0    sp|A0A089QRB9|MSL3_MYCTU
1    sp|A0A089QRB9|MSL3_MYCTU
2    sp|A0A089QRB9|MSL3_MYCTU
3    sp|A0A089QRB9|MSL3_MYCTU
4    sp|A0A089QRB9|MSL3_MYCTU
Name: protein_id, dtype: object

In [8]:
homo_ids = blast_df['protein_id']

In [9]:
filtered_bact="/content/drive/MyDrive/Subtractive Genomics Approach/m_tuberculosis_filtered.fasta"

In [21]:
with open(filtered_bact, "r") as handle:
    bact_dict = SeqIO.to_dict(SeqIO.parse(handle, "fasta"))
bact_dict

{'sp|A0A089QRB9|MSL3_MYCTU': SeqRecord(seq=Seq('MRTATATSVAVIGMACRLPGGIDSPQRLWEALLRGDDLVGEIPADRWDANVYYD...APV'), id='sp|A0A089QRB9|MSL3_MYCTU', name='sp|A0A089QRB9|MSL3_MYCTU', description='sp|A0A089QRB9|MSL3_MYCTU Mycolipanoate synthase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=msl3 PE=1 SV=2', dbxrefs=[]),
 'sp|I6WXK4|PTPB_MYCTU': SeqRecord(seq=Seq('MAVRELPGAWNFRDVADTATALRPGRLFRSSELSRLDDAGRATLRRLGITDVAD...LLG'), id='sp|I6WXK4|PTPB_MYCTU', name='sp|I6WXK4|PTPB_MYCTU', description='sp|I6WXK4|PTPB_MYCTU Triple specificity protein phosphatase PtpB OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=ptpB PE=1 SV=1', dbxrefs=[]),
 'sp|I6WZG6|ENCAP_MYCTU': SeqRecord(seq=Seq('MNNLYRDLAPVTEAAWAEIELEAARTFKRHIAGRRVVDVSDPGGPVTAAVSTGR...LSH'), id='sp|I6WZG6|ENCAP_MYCTU', name='sp|I6WZG6|ENCAP_MYCTU', description='sp|I6WZG6|ENCAP_MYCTU Type 1 encapsulin shell protein OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=enc PE=1 SV=1', dbxrefs=[]),
 'sp|I6X235|ADPP_MYCTU': SeqRecord(seq=Seq('MAEHDFETISSETLHTGAIFALRRDQVRMPGGGIVTREVVEHFGAVAIVAMDDN...AER'), id='sp|I6X235|ADPP_MYCTU', name='sp|I6X235|ADPP_MYCTU', description='sp|I6X235|ADPP_MYCTU ADP-ribose pyrophosphatase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv1700 PE=1 SV=1', dbxrefs=[]),
 'sp|I6X5W1|VKOR_MYCTU': SeqRecord(seq=Seq('MVAARPAERSGDPAAVRVPVPSAWWVLIGGVIGLFASMTLTVEKVRILLDPIYV...TLI'), id='sp|I6X5W1|VKOR_MYCTU', name='sp|I6X5W1|VKOR_MYCTU', description='sp|I6X5W1|VKOR_MYCTU Vitamin K epoxide reductase homolog OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=vkoR PE=1 SV=1', dbxrefs=[]),
 'sp|I6X8D2|PKS13_MYCTU': SeqRecord(seq=Seq('MADVAESQENAPAERAELTVPEMRQWLRNWVGKAVGKAPDSIDESVPMVELGLS...GKQ'), id='sp|I6X8D2|PKS13_MYCTU', name='sp|I6X8D2|PKS13_MYCTU', description='sp|I6X8D2|PKS13_MYCTU Polyketide synthase Pks13 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=pks13 PE=1 SV=1', dbxrefs=[]),
 'sp|I6XD65|PNCA_MYCTU': SeqRecord(seq=Seq('MRALIIVDVQNDFCEGGSLAVTGGAALARAISDYLAEAADYHHVVATKDFHIDP...CSS'), id='sp|I6XD65|PNCA_MYCTU', name='sp|I6XD65|PNCA_MYCTU', description='sp|I6XD65|PNCA_MYCTU Nicotinamidase/pyrazinamidase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=pncA PE=1 SV=1', dbxrefs=[]),
 'sp|I6XD69|PKS12_MYCTU': SeqRecord(seq=Seq('MVDQLQHATEALRKALVQVERLKRTNRALLERSSEPIAIVGMSCRFPGGVDSPE...DDE'), id='sp|I6XD69|PKS12_MYCTU', name='sp|I6XD69|PKS12_MYCTU', description='sp|I6XD69|PKS12_MYCTU Mycoketide-CoA synthase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=pks12 PE=1 SV=1', dbxrefs=[]),
 'sp|I6XFS7|RDMTR_MYCTU': SeqRecord(seq=Seq('MTRIIGGVAGGRRIAVPPRGTRPTTDRVRESLFNIVTARRDLTGLAVLDLYAGS...ANV'), id='sp|I6XFS7|RDMTR_MYCTU', name='sp|I6XFS7|RDMTR_MYCTU', description='sp|I6XFS7|RDMTR_MYCTU RNA/DNA methyltransferase Rv2966c OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv2966c PE=1 SV=1', dbxrefs=[]),
 'sp|I6XHI4|FADA5_MYCTU': SeqRecord(seq=Seq('MGYPVIVEATRSPIGKRNGWLSGLHATELLGAVQKAVVDKAGIQSGLHAGDVEQ...ERI'), id='sp|I6XHI4|FADA5_MYCTU', name='sp|I6XHI4|FADA5_MYCTU', description='sp|I6XHI4|FADA5_MYCTU Steroid 3-ketoacyl-CoA thiolase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=fadA5 PE=1 SV=1', dbxrefs=[]),
 'sp|I6XU97|EST45_MYCTU': SeqRecord(seq=Seq('MLSDDELTGLDEFALLAENAEQAGVNGPLPEVERVQAGAISALRWGGSAPRVIF...DTR'), id='sp|I6XU97|EST45_MYCTU', name='sp|I6XU97|EST45_MYCTU', description='sp|I6XU97|EST45_MYCTU Esterase Rv0045c OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv0045c PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y0R5|FOLC_MYCTU': SeqRecord(seq=Seq('MNSTNSGPPDSGSATGVVPTPDEIASLLQVEHLLDQRWPETRIDPSLTRISALM...DPQ'), id='sp|I6Y0R5|FOLC_MYCTU', name='sp|I6Y0R5|FOLC_MYCTU', description='sp|I6Y0R5|FOLC_MYCTU Dihydrofolate synthase/folylpolyglutamate synthase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=folC PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y1Q2|MNTR_MYCTU': SeqRecord(seq=Seq('MRADEEPGDLSAVAQDYLKVIWTAQEWSQDKVSTKMLAERIGVSASTASESIRK...VVS'), id='sp|I6Y1Q2|MNTR_MYCTU', name='sp|I6Y1Q2|MNTR_MYCTU', description='sp|I6Y1Q2|MNTR_MYCTU Manganese-dependent transcriptional repressor MntR OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=mntR PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y2J4|LIPY_MYCTU': SeqRecord(seq=Seq('MVSYVVALPEVMSAAATDVASIGSVVATASQGVAGATTTVLAAAEDEVSAAIAA...IAA'), id='sp|I6Y2J4|LIPY_MYCTU', name='sp|I6Y2J4|LIPY_MYCTU', description='sp|I6Y2J4|LIPY_MYCTU Triacylglycerol lipase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=lipY PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y3Q0|CHSE5_MYCTU': SeqRecord(seq=Seq('MDFTTTEAAQDLGGLVDTIVDAVCTPEHQRELDKLEQRFDRELWRKLIDAGILS...TPA'), id='sp|I6Y3Q0|CHSE5_MYCTU', name='sp|I6Y3Q0|CHSE5_MYCTU', description='sp|I6Y3Q0|CHSE5_MYCTU Acyl-CoA dehydrogenase FadE27 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=fadE27 PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y4D2|PEPAM_MYCTU': SeqRecord(seq=Seq('MIVGVLVAAATPIISSASATPANIAGMVVFIDPGHNGANDASIGRQVPTGRGGT...QAR'), id='sp|I6Y4D2|PEPAM_MYCTU', name='sp|I6Y4D2|PEPAM_MYCTU', description='sp|I6Y4D2|PEPAM_MYCTU N-acetylmuramoyl-L-alanine amidase Rv3717 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv3717 PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y4U9|DYP_MYCTU': SeqRecord(seq=Seq('MAVPAVSPQPILAPLTPAAIFLVATIGADGEATVHDALSKISGLVRAIGFRDPT...SPR'), id='sp|I6Y4U9|DYP_MYCTU', name='sp|I6Y4U9|DYP_MYCTU', description='sp|I6Y4U9|DYP_MYCTU Dye-decolorizing peroxidase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=dyp PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y778|FABG4_MYCTU': SeqRecord(seq=Seq('MAPKRSSDLFSQVVNSGPGSFLARQLGVPQPETLRRYRAGEPPLTGSLLIGGAG...IGA'), id='sp|I6Y778|FABG4_MYCTU', name='sp|I6Y778|FABG4_MYCTU', description='sp|I6Y778|FABG4_MYCTU 3-oxoacyl-[acyl-carrier-protein] reductase [NADH] OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=fabG4 PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y9J2|LDT2_MYCTU': SeqRecord(seq=Seq('MPKVGIAAQAGRTRVRRAWLTALMMTAVMIGAVACGSGRGPAPIKVIADKGTPF...AKA'), id='sp|I6Y9J2|LDT2_MYCTU', name='sp|I6Y9J2|LDT2_MYCTU', description='sp|I6Y9J2|LDT2_MYCTU L,D-transpeptidase 2 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=ldtB PE=1 SV=1', dbxrefs=[]),
 'sp|I6Y9Q3|PRPC_MYCTU': SeqRecord(seq=Seq('MTGPLAAARSVAATKSMTAPTVDERPDIKKGLAGVVVDTTAISKVVPQTNSLTY...GTF'), id='sp|I6Y9Q3|PRPC_MYCTU', name='sp|I6Y9Q3|PRPC_MYCTU', description='sp|I6Y9Q3|PRPC_MYCTU 2-methylcitrate synthase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=prpC PE=1 SV=1', dbxrefs=[]),
 'sp|I6YBQ3|LRPA_MYCTU': SeqRecord(seq=Seq('MNEALDDIDRILVRELAADGRATLSELATRAGLSVSAVQSRVRRLESRGVVQGY...HIP'), id='sp|I6YBQ3|LRPA_MYCTU', name='sp|I6YBQ3|LRPA_MYCTU', description='sp|I6YBQ3|LRPA_MYCTU HTH-type transcriptional regulator LrpA OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=lrpA PE=1 SV=1', dbxrefs=[]),
 'sp|I6YCA3|CHSE4_MYCTU': SeqRecord(seq=Seq('MRISYTPQQEELRRELRSYFATLMTPERREALSSVQGEYGVGNVYRETIAQMGR...ANR'), id='sp|I6YCA3|CHSE4_MYCTU', name='sp|I6YCA3|CHSE4_MYCTU', description='sp|I6YCA3|CHSE4_MYCTU Acyl-CoA dehydrogenase FadE26 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=fadE26 PE=1 SV=1', dbxrefs=[]),
 'sp|I6YFP0|BIRA_MYCTU': SeqRecord(seq=Seq('MTDRDRLRPPLDERSLRDQLIGAGSGWRQLDVVAQTGSTNADLLARAASGADID...HLR'), id='sp|I6YFP0|BIRA_MYCTU', name='sp|I6YFP0|BIRA_MYCTU', description='sp|I6YFP0|BIRA_MYCTU Biotin--[acetyl-CoA-carboxylase] ligase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=birA PE=1 SV=1', dbxrefs=[]),
 'sp|I6YG32|RIMI_MYCTU': SeqRecord(seq=Seq('MTADTEPVTIGALTRADAQRCAELEAQLFVGDDPWPPAAFNRELASPHNHYVGA...DPS'), id='sp|I6YG32|RIMI_MYCTU', name='sp|I6YG32|RIMI_MYCTU', description='sp|I6YG32|RIMI_MYCTU N-alpha-acetyltransferase RimI OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=rimI PE=1 SV=1', dbxrefs=[]),
 'sp|I6YGX2|PBPA2_MYCTU': SeqRecord(seq=Seq('MPERLPAAITVLKLAGCCLLASVVATALTFPFAGGLGLMSNRASEVVANGSAQL...PPP'), id='sp|I6YGX2|PBPA2_MYCTU', name='sp|I6YGX2|PBPA2_MYCTU', description='sp|I6YGX2|PBPA2_MYCTU Penicillin-binding protein A2 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=ponA2 PE=1 SV=1', dbxrefs=[]),
 'sp|I6YHB0|HNSLK_MYCTU': SeqRecord(seq=Seq('MPDPQDRPDSEPSDASTPPAKKLPAKKAAKKAPARKTPAKKAPAKKTPAKGAKS...RRR'), id='sp|I6YHB0|HNSLK_MYCTU', name='sp|I6YHB0|HNSLK_MYCTU', description='sp|I6YHB0|HNSLK_MYCTU Histone-like protein Rv3852 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=hns PE=1 SV=2', dbxrefs=[]),
 'sp|L0T905|RSEA_MYCTU': SeqRecord(seq=Seq('MADPGSVGHVFRRAFSWLPAQFASQSDAPVGAPRQFRSTEHLSIEAIAAFVDGE...VRR'), id='sp|L0T905|RSEA_MYCTU', name='sp|L0T905|RSEA_MYCTU', description='sp|L0T905|RSEA_MYCTU Anti-sigma-E factor RseA OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=rseA PE=1 SV=1', dbxrefs=[]),
 'sp|L0T911|PBPB_MYCTU': SeqRecord(seq=Seq('MSRAAPRRASQSQSTRPARGLRRPPGAQEVGQRKRPGKTQKARQAQEATKSRPA...QAT'), id='sp|L0T911|PBPB_MYCTU', name='sp|L0T911|PBPB_MYCTU', description='sp|L0T911|PBPB_MYCTU Penicillin-binding protein PbpB OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=pbpB PE=1 SV=1', dbxrefs=[]),
 'sp|L0TC47|LIPV_MYCTU': SeqRecord(seq=Seq('MIIDLHVQRYGPSGPARVLTIHGVTEHGRIWHRLAHHLPEIPIAAPDLLGHGRS...GPR'), id='sp|L0TC47|LIPV_MYCTU', name='sp|L0TC47|LIPV_MYCTU', description='sp|L0TC47|LIPV_MYCTU Lipase LipV OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=lipV PE=1 SV=2', dbxrefs=[]),
 'sp|O05306|LOGH_MYCTU': SeqRecord(seq=Seq('MSAKIDITGDWTVAVYCAASPTHAELLELAAEVGAAIAGRGWTLVWGGGHVSAM...APS'), id='sp|O05306|LOGH_MYCTU', name='sp|O05306|LOGH_MYCTU', description="sp|O05306|LOGH_MYCTU Cytokinin riboside 5'-monophosphate phosphoribohydrolase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=log PE=1 SV=1", dbxrefs=[]),
 'sp|O05307|FAC6_MYCTU': SeqRecord(seq=Seq('MSDYYGGAHTTVRLIDLATRMPRVLADTPVIVRGAMTGLLARPNSKASIGTVFQ...PQG'), id='sp|O05307|FAC6_MYCTU', name='sp|O05307|FAC6_MYCTU', description='sp|O05307|FAC6_MYCTU Medium/long-chain-fatty-acid--CoA ligase FadD6 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=fadD6 PE=1 SV=1', dbxrefs=[]),
 'sp|O05318|MEPRM_MYCTU': SeqRecord(seq=Seq('MSSTVIDRARPAGHRAPHRGSGFTGTLGLLRLYLRRDRVSLPLWVLLLSVPLAT...VRC'), id='sp|O05318|MEPRM_MYCTU', name='sp|O05318|MEPRM_MYCTU', description='sp|O05318|MEPRM_MYCTU Multidrug efflux system permease protein Rv1217c OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv1217c PE=1 SV=1', dbxrefs=[]),
 'sp|O05442|CPNT_MYCTU': SeqRecord(seq=Seq('MAPLAVDPAALDSAGGAVVAAGAGLGAVISSLTAALAGCAGMAGDDPAGAVFGR...LRQ'), id='sp|O05442|CPNT_MYCTU', name='sp|O05442|CPNT_MYCTU', description='sp|O05442|CPNT_MYCTU Outer membrane channel protein CpnT OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=cpnT PE=1 SV=1', dbxrefs=[]),
 'sp|O05461|MYCP1_MYCTU': SeqRecord(seq=Seq('MHRIFLITVALALLTASPASAITPPPIDPGALPPDVTGPDQPTEQRVLCASPTT...SRR'), id='sp|O05461|MYCP1_MYCTU', name='sp|O05461|MYCP1_MYCTU', description='sp|O05461|MYCP1_MYCTU Mycosin-1 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=mycP1 PE=1 SV=1', dbxrefs=[]),
 'sp|O05581|PAT_MYCTU': SeqRecord(seq=Seq('MDGIAELTGARVEDLAGMDVFQGCPAEGLVSLAASVQPLRAAAGQVLLRQGEPA...AVG'), id='sp|O05581|PAT_MYCTU', name='sp|O05581|PAT_MYCTU', description='sp|O05581|PAT_MYCTU Acetyltransferase Pat OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv0998 PE=1 SV=2', dbxrefs=[]),
 'sp|O05858|FASR_MYCTU': SeqRecord(seq=Seq('MSDLAKTAQRRALRSSGSARPDEDVPAPNRRGNRLPRDERRGQLLVVASDVFVD...TRS'), id='sp|O05858|FASR_MYCTU', name='sp|O05858|FASR_MYCTU', description='sp|O05858|FASR_MYCTU HTH-type transcriptional activator FasR OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=fasR PE=1 SV=1', dbxrefs=[]),
 'sp|O05877|PK21_MYCTU': SeqRecord(seq=Seq('MDIPSVDVSTATNDGASSRAKGHRSAAPGRRKISDAVYQAELFRLQTEFVKLQE...IAR'), id='sp|O05877|PK21_MYCTU', name='sp|O05877|PK21_MYCTU', description='sp|O05877|PK21_MYCTU GDP-polyphosphate phosphotransferase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=ppk2 PE=1 SV=1', dbxrefs=[]),
 'sp|O06218|AHPR_MYCTU': SeqRecord(seq=Seq('MKFVNHIEPVAPRRAGGAVAEVYAEARREFGRLPEPLAMLSPDEGLLTAGWATL...PTG'), id='sp|O06218|AHPR_MYCTU', name='sp|O06218|AHPR_MYCTU', description='sp|O06218|AHPR_MYCTU Alkyl hydroperoxide reductase Rv2159c OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv2159c PE=1 SV=1', dbxrefs=[]),
 'sp|O06319|CULP4_MYCTU': SeqRecord(seq=Seq('MIPRPQPHSGRWRAGAARRLTSLVAAAFAAATLLLTPALAPPASAGCPDAEVVF...SRI'), id='sp|O06319|CULP4_MYCTU', name='sp|O06319|CULP4_MYCTU', description='sp|O06319|CULP4_MYCTU Phospholipase Culp4 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=cut4 PE=1 SV=3', dbxrefs=[]),
 'sp|O06350|LIPF_MYCTU': SeqRecord(seq=Seq('MSSYYARRPLQSSGCSNSDSCWDGAPIEITESGPSVAGRLAALASRMTIKPLMT...SPI'), id='sp|O06350|LIPF_MYCTU', name='sp|O06350|LIPF_MYCTU', description='sp|O06350|LIPF_MYCTU Carboxylesterase/phospholipase LipF OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=lipF PE=1 SV=4', dbxrefs=[]),
 'sp|O06428|NPPPS_MYCTU': SeqRecord(seq=Seq('MRTPATVVAGVDLGDAVFAAAVRAGVARVEQLMDTELRQADEVMSDSLLHLFNA...RHG'), id='sp|O06428|NPPPS_MYCTU', name='sp|O06428|NPPPS_MYCTU', description='sp|O06428|NPPPS_MYCTU Nonaprenyl diphosphate synthase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=grcC1 PE=1 SV=1', dbxrefs=[]),
 'sp|O06543|AMACR_MYCTU': SeqRecord(seq=Seq('MAGPLSGLRVVELAGIGPGPHAAMILGDLGADVVRIDRPSSVDGISRDAMLRNR...WDG'), id='sp|O06543|AMACR_MYCTU', name='sp|O06543|AMACR_MYCTU', description='sp|O06543|AMACR_MYCTU Alpha-methylacyl-CoA racemase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=mcr PE=1 SV=3', dbxrefs=[]),
 'sp|O06582|PRPD_MYCTU': SeqRecord(seq=Seq('MPDQDTKVRFFRVFCWCPVLRMVRIMLMHAVRAWRSADDFPCTEHMAYKIAQVA...IFR'), id='sp|O06582|PRPD_MYCTU', name='sp|O06582|PRPD_MYCTU', description='sp|O06582|PRPD_MYCTU 2-methylcitrate dehydratase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=prpD PE=1 SV=1', dbxrefs=[]),
 'sp|O06769|NCASE_MYCTU': SeqRecord(seq=Seq('MLSVGRGIADITGEAADCGMLGYGKSDQRTAGIHQRLRSRAFVFRDDSQDGDAR...TVV'), id='sp|O06769|NCASE_MYCTU', name='sp|O06769|NCASE_MYCTU', description='sp|O06769|NCASE_MYCTU Neutral ceramidase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv0669c PE=1 SV=1', dbxrefs=[]),
 'sp|O07427|MGLL_MYCTU': SeqRecord(seq=Seq('MTTTRTERNFAGIGDVRIVYDVWTPDTAPQAVVVLAHGLGEHARRYDHVAQRLG...ERL'), id='sp|O07427|MGLL_MYCTU', name='sp|O07427|MGLL_MYCTU', description='sp|O07427|MGLL_MYCTU Monoacylglycerol lipase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv0183 PE=1 SV=2', dbxrefs=[]),
 'sp|O07732|LIPJ_MYCTU': SeqRecord(seq=Seq('MAQAPHIHRTRYAKCGDMDIAYQVLGDGPTDLLVLPGPFVPIDSIDDEPSLYRF...RTR'), id='sp|O07732|LIPJ_MYCTU', name='sp|O07732|LIPJ_MYCTU', description='sp|O07732|LIPJ_MYCTU Bifunctional lipase/adenylate cyclase LipJ OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=lipJ PE=1 SV=1', dbxrefs=[]),
 'sp|O07783|VAPC4_MYCTU': SeqRecord(seq=Seq('MNVRRALADTSVFIGIEATRFDPDRFAGYEWGVSVVTLGELRLGVLQASGPEAA...ITI'), id='sp|O07783|VAPC4_MYCTU', name='sp|O07783|VAPC4_MYCTU', description='sp|O07783|VAPC4_MYCTU Ribonuclease VapC4 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=vapC4 PE=1 SV=3', dbxrefs=[]),
 'sp|O33194|G3PP_MYCTU': SeqRecord(seq=Seq('MKSIAQEHDCLLIDLDGTVFCGRQPTGGAVQSLSQVRSRKLFVTNNASRSADEV...GTQ'), id='sp|O33194|G3PP_MYCTU', name='sp|O33194|G3PP_MYCTU', description='sp|O33194|G3PP_MYCTU D-glycerol 3-phosphate phosphatase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv1692 PE=1 SV=1', dbxrefs=[]),
 'sp|O33272|DSBA_MYCTU': SeqRecord(seq=Seq('MADKSKRPPRFDLKSADGSFGRLVQIGGTTIVVVFAVVLVFYIVTSRDDKKDGV...ATS'), id='sp|O33272|DSBA_MYCTU', name='sp|O33272|DSBA_MYCTU', description='sp|O33272|DSBA_MYCTU Disulfide oxidase DsbA OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=dsbA PE=1 SV=3', dbxrefs=[]),
 'sp|O33283|EPHG_MYCTU': SeqRecord(seq=Seq('MAELTETSPETPETTEAIRAVEAFLNALQNEDFDTVDAALGDDLVYENVGFSRI...ATL'), id='sp|O33283|EPHG_MYCTU', name='sp|O33283|EPHG_MYCTU', description='sp|O33283|EPHG_MYCTU Epoxide hydrolase EphG OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=ephG PE=1 SV=1', dbxrefs=[]),
 'sp|O33289|ARGA_MYCTU': SeqRecord(seq=Seq('MTERPRDCRPVVRRARTSDVPAIKQLVDTYAGKILLEKNLVTLYEAVQEFWVAE...LVL'), id='sp|O33289|ARGA_MYCTU', name='sp|O33289|ARGA_MYCTU', description='sp|O33289|ARGA_MYCTU Amino-acid acetyltransferase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=argA PE=1 SV=1', dbxrefs=[]),
 'sp|O33336|PPTT_MYCTU': SeqRecord(seq=Seq('MTVGTLVASVLPATVFEDLAYAELYSDPPGLTPLPEEAPLIARSVAKRRNEFIT...IVL'), id='sp|O33336|PPTT_MYCTU', name='sp|O33336|PPTT_MYCTU', description="sp|O33336|PPTT_MYCTU 4'-phosphopantetheinyl transferase PptT OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=pptT PE=1 SV=1", dbxrefs=[]),
 'sp|O33363|GDSL_MYCTU': SeqRecord(seq=Seq('MSRPGTYVIGLTLLVGLVVGNPGCPRSYRPLTLDYRLNPVAVIGDSYTTGTDEG...LVG'), id='sp|O33363|GDSL_MYCTU', name='sp|O33363|GDSL_MYCTU', description='sp|O33363|GDSL_MYCTU GDSL lipase Rv0518 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv0518 PE=1 SV=1', dbxrefs=[]),
 'sp|O50406|DITCY_MYCTU': SeqRecord(seq=Seq('METFRTLLAKAALGNGISSTAYDTAWVAKLGQLDDELSDLALNWLCERQLPDGS...SNQ'), id='sp|O50406|DITCY_MYCTU', name='sp|O50406|DITCY_MYCTU', description='sp|O50406|DITCY_MYCTU Type B diterpene cyclase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=Rv3377c PE=1 SV=1', dbxrefs=[]),
 'sp|O53166|ACNA_MYCTU': SeqRecord(seq=Seq('MTSKSVNSFGAHDTLKVGEKSYQIYRLDAVPNTAKLPYSLKVLAENLLRNEDGS...KSG'), id='sp|O53166|ACNA_MYCTU', name='sp|O53166|ACNA_MYCTU', description='sp|O53166|ACNA_MYCTU Aconitate hydratase A OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=acn PE=1 SV=1', dbxrefs=[]),
 'sp|O53168|RIPA_MYCTU': SeqRecord(seq=Seq('MRRNRRGSPARPAARFVRPAIPSALSVALLVCTPGLATADPQTDTIAALIADVA...IEY'), id='sp|O53168|RIPA_MYCTU', name='sp|O53168|RIPA_MYCTU', description='sp|O53168|RIPA_MYCTU Peptidoglycan endopeptidase RipA OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=ripA PE=1 SV=1', dbxrefs=[]),
 'sp|O53177|RPFE_MYCTU': SeqRecord(seq=Seq('MKNARTTLIAAAIAGTLVTTSPAGIANADDAGLDPNAAAGPDAVGFDPNLPPAP...RRG'), id='sp|O53177|RPFE_MYCTU', name='sp|O53177|RPFE_MYCTU', description='sp|O53177|RPFE_MYCTU Resuscitation-promoting factor RpfE OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=rpfE PE=1 SV=1', dbxrefs=[]),
 'sp|O53181|KORB_MYCTU': SeqRecord(seq=Seq('MTRSGDEAQLMTGVTGDLAGTELGLTPSLTKNAGVPTTDQPQKGKDFTSDQEVR...TVD'), id='sp|O53181|KORB_MYCTU', name='sp|O53181|KORB_MYCTU', description='sp|O53181|KORB_MYCTU 2-oxoglutarate oxidoreductase subunit KorB OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=korB PE=1 SV=1', dbxrefs=[]),
 'sp|O53289|SERB2_MYCTU': SeqRecord(seq=Seq('MPAKVSVLITVTGMDQPGVTSALFEVLAQHGVELLNVEQVVIRGRLTLGVLVSC...PAD'), id='sp|O53289|SERB2_MYCTU', name='sp|O53289|SERB2_MYCTU', description='sp|O53289|SERB2_MYCTU Phosphoserine phosphatase SerB2 OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=serB2 PE=1 SV=1', dbxrefs=[]),
 'sp|O53361|SAPM_MYCTU': SeqRecord(seq=Seq('MLRGIQALSRPLTRVYRALAVIGVLAASLLASWVGAVPQVGLAASALPTFAHVV...WGD'), id='sp|O53361|SAPM_MYCTU', name='sp|O53361|SAPM_MYCTU', description='sp|O53361|SAPM_MYCTU Phosphatidylinositol-3-phosphatase OS=Mycobacterium tuberculosis (strain ATCC 25618 / H37Rv) OX=83332 GN=sapM PE=1 SV=1', dbxrefs=[]),

In [18]:
bact_series = pd.Series(bact_dict)
bact_series

sp|A0A089QRB9|MSL3_MYCTU    (M, R, T, A, T, A, T, S, V, A, V, I, G, M, A, ...
sp|I6WXK4|PTPB_MYCTU        (M, A, V, R, E, L, P, G, A, W, N, F, R, D, V, ...
sp|I6WZG6|ENCAP_MYCTU       (M, N, N, L, Y, R, D, L, A, P, V, T, E, A, A, ...
sp|I6X235|ADPP_MYCTU        (M, A, E, H, D, F, E, T, I, S, S, E, T, L, H, ...
sp|I6X5W1|VKOR_MYCTU        (M, V, A, A, R, P, A, E, R, S, G, D, P, A, A, ...
                                                  ...
tr|Q79FZ8|Q79FZ8_MYCTU      (M, S, R, W, K, Q, G, W, T, R, G, S, L, F, A, ...
tr|Q79G05|Q79G05_MYCTU      (M, R, C, R, P, P, S, R, N, R, S, A, H, T, A, ...
tr|Q79G06|Q79G06_MYCTU      (M, A, P, F, G, F, T, P, K, A, R, H, N, R, G, ...
tr|Q79G08|Q79G08_MYCTU      (M, S, F, V, S, V, A, P, E, I, V, V, A, A, A, ...
tr|V5QQS8|V5QQS8_MYCTU      (M, A, I, D, P, A, A, A, Y, A, S, A, I, R, T, ...
Length: 3658, dtype: object

In [22]:
clean_series = bact_series.drop(homo_ids)

In [23]:
non_homo_bact = list(clean_series)

In [24]:
len(non_homo_bact)

2515

In [17]:
from Bio import SeqIO


SeqIO.write(non_homo_bact, "m_tuberculosis_non_homologous.fasta", "fasta")

2515

In [ ]:
from Bio import SeqIO


SeqIO.write(non_homo_bact, "/content/drive/MyDrive/Subtractive Genomics Approach/m_tuberculosis_non_homologous.fasta", "fasta")